server:
  port: 9292
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/FuDocs
    username: root
    password: root
  jpa:    show-sql: true
    hibernate:      ddl-auto: none
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect